name: Exemplo Artifact
run-name: Exemplo Workflow para artifact, executado por ${{ github.actor }}

on:
  workflow_dispatch:

env:
  nome-artefato: manipulacao-artefatos

jobs:
  upload-artfact:
    runs-on: ubuntu-latest
    steps:
      - name: Geração de arquivos
        run: |
          mkdir -p artefatos
          echo "Arquivo de artefato 01" > ./artefatos/primeiro_arquivo.txt
          echo "Arquivo de artefato 02" > ./artefatos/segundo_arquivo.txt
          echo "Arquivo de artefato 03" > ./artefatos/terceiro_arquivo.txt
          echo "Arquivo de artefato 04" > ./artefatos/quarto_arquivo.txt

      - name: Verificação dos arquivos
        run: ls -lh ./artefatos

      - name: Upload dos arquivos como artefato
        uses: actions/upload-artifact@v4
        with:
          name: manipulacao-artefatos
          path: ./artefatos

      - name: Confirmação do envio
        run: echo "Artefatos enviados com sucesso."

  download-artfact:
    runs-on: ubuntu-latest
    needs: [upload-artfact]
    steps:
      - name: Download dos artefatos
        uses: actions/download-artifact@v4
        with:
          name: manipulacao-artefatos
          path: ./artefatos

      - name: Verificação de arquivos baixados
        run: ls -lh ./artefatos
