name: Exemplo Artfact
run-name: Exemplo Workflow para artfact, executado por ${{ github.actor }}

on:
  workflow_dispatch:

env:
    nome_artefato: manipulacao-artefatos

jobs:
  upload-artfact:
    runs-on: ubuntu-latest
    steps:
      - name: Listagem de arquivos
        run: ls
      - name: Geração de arquivos
        run: |
            mkdir artefatos
            echo "Arquivo de artefato 01" > ./artefatos/primeiro_arquivo.txt
            echo "Arquivo de artefato 02" > ./artefatos/segundo_arquivo.txt
            echo "Arquivo de artefato 03" > ./artefatos/terceiro_arquivo.txt
            echo "Arquivo de artefato 04" > ./artefatos/quarto_arquivo.txt

      - name: Envio dos arquivos
        uses: actions/upload-artifact@v4
        id: upload-artifact 
        with:
            name: ${{ env.nome_artefato }}
            path: ./artefatos

      - name: Listagem de arquivos
        run: ls ./artefatos

      - name: Endereço dos artefatos
        run: |
          echo "Artefatos enviados com sucesso com o nome: ${{ env.nome_artefato }}"

  download-artfact:
    runs-on: ubuntu-latest
    needs: [upload-artfact]
    steps:
      - name: Listagem de arquivos
        run: ls

      - name: Download dos artefatos
        uses: actions/download-artifact@v4
        with:
            name: ${{ env.nome_artefato }}

      - name: Listagem de arquivos
        run: ls