name: Exemplo Output
run-name: Exemplo Workflow para output, executado por ${{ github.actor }}

on:
  workflow_dispatch:
jobs:
  gerando_output:
    runs-on: ubuntu-latest
    steps:
        - name: Gerando output com shell
          id: exemplo-output
          run: |
            ACTION_RONDOM=$(( $RONDOM ))
            echo "action_random=$ACTION_RONDOM" >> $GITHUB_OUTPUT

        - name: Resultado do output da action de exemplo
          run: echo "${{ steps.exemplo-output.outputs.action_random }}"